-- Phase 1: classified write gate.
-- Every criterion proposal must declare a fact class and pass through
-- public.apply_classified_claim. Direct criterion DML is neutralised and audited.

ALTER TABLE public.companies
  ADD COLUMN IF NOT EXISTS lifecycle_state text,
  ADD COLUMN IF NOT EXISTS proceeding_type text,
  ADD COLUMN IF NOT EXISTS additionality_state text,
  ADD COLUMN IF NOT EXISTS additionality_substitute text,
  ADD COLUMN IF NOT EXISTS additionality_dimension text,
  ADD COLUMN IF NOT EXISTS additionality_rationale text;

ALTER TABLE public.criterion_reviews
  ADD COLUMN IF NOT EXISTS fact_class text,
  ADD COLUMN IF NOT EXISTS writer_lane text,
  ADD COLUMN IF NOT EXISTS source_reference text;

ALTER TABLE public.secondary_criterion_reviews
  ADD COLUMN IF NOT EXISTS fact_class text,
  ADD COLUMN IF NOT EXISTS writer_lane text,
  ADD COLUMN IF NOT EXISTS source_reference text;

ALTER TABLE public.secondary_company_reviews
  ADD COLUMN IF NOT EXISTS proposed_publication_scope text,
  ADD COLUMN IF NOT EXISTS proposed_lifecycle_state text,
  ADD COLUMN IF NOT EXISTS proposed_proceeding_type text;

CREATE TABLE IF NOT EXISTS public.company_funding (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  round_type text,
  announced_on date,
  amount numeric,
  currency text,
  amount_disclosed boolean NOT NULL,
  source_url text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.company_exit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  exit_type text,
  announced_on date,
  amount numeric,
  currency text,
  amount_disclosed boolean NOT NULL,
  acquirer text,
  source_url text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE SCHEMA IF NOT EXISTS qa_monitor;

CREATE TABLE IF NOT EXISTS qa_monitor.claim_write_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempted_at timestamptz NOT NULL DEFAULT now(),
  writer_lane text,
  company_id bigint,
  company_name text,
  target_table text,
  target_criterion smallint,
  declared_fact_class text,
  detected_fact_class text,
  proposed_verdict text,
  claim_text text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  expected_destination text,
  outcome text NOT NULL,
  reason text,
  source_reference text,
  db_user text NOT NULL DEFAULT current_user,
  application_name text DEFAULT current_setting('application_name', true)
);

CREATE INDEX IF NOT EXISTS idx_claim_write_audit_attempted
  ON qa_monitor.claim_write_audit (attempted_at DESC);

CREATE INDEX IF NOT EXISTS idx_claim_write_audit_company
  ON qa_monitor.claim_write_audit (company_id, attempted_at DESC);

CREATE TABLE IF NOT EXISTS qa_monitor.claim_gate_fixtures (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fixture_key text NOT NULL UNIQUE,
  company_name text NOT NULL,
  criterion smallint NOT NULL,
  claim_text text NOT NULL,
  expected_fact_class text NOT NULL,
  expected_destination text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION qa_monitor.detect_fact_class(p_claim text)
RETURNS text
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  s text := lower(COALESCE(p_claim, ''));
BEGIN
  -- Exact regression signature: these 20 C8 rationales mixed entity liveness
  -- into a structural criterion, even when the status sentence mentions an acquisition.
  IF s ~ 'autonomy is structurally disqualifying or under review:' THEN
    RETURN 'liveness';
  END IF;

  IF s ~ 'publication_scope|out_of_scope'
     OR s ~ '\m(listed company|public company|ipo|euronext|nasdaq|nyse|acquired|acquisition|delisted)\M' THEN
    RETURN 'scope';
  END IF;

  IF s ~ 'cash runway|funding round|debt facility|financing condition|raised [€$£]|amount disclosed|exit amount' THEN
    RETURN 'finance';
  END IF;

  IF s ~ '\m(inactive|out of business|dissolved|forfeited|liquidated|liquidation|deregistered|bankrupt|insolvent|dormant)\M'
     OR s ~ 'safeguard procedure|under (court |judicial )?protection|redressement|continuation plan' THEN
    RETURN 'liveness';
  END IF;

  IF s ~ 'missed (its|the) .*primary endpoint'
     OR s ~ 'single-arm|lacked (a )?sham|sham control|could not attribute|efficacy uncertainty'
     OR s ~ 'meaning-changing errors|remain(s|ed)? unresolved'
     OR s ~ 'not (yet )?(validated|demonstrated|proven|commercialised|commercialized)'
     OR s ~ '(insufficient|limited|weak|missing|lacks?|without) (independent )?(evidence|validation|data|outcome|trial)'
     OR s ~ '(awaiting|pending) .*results|evidence[- ]maturity|readiness condition' THEN
    RETURN 'readiness';
  END IF;

  RETURN 'structural';
END
$$;

CREATE OR REPLACE FUNCTION qa_monitor.destination_for_fact_class(p_fact_class text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE p_fact_class
    WHEN 'structural' THEN 'criterion_reviews'
    WHEN 'readiness' THEN 'companies.what_it_needs_to_qualify'
    WHEN 'liveness' THEN 'companies.lifecycle_state'
    WHEN 'scope' THEN 'companies.publication_scope'
    WHEN 'finance' THEN 'company_funding/company_exit'
    ELSE 'rejected'
  END
$$;

CREATE OR REPLACE FUNCTION qa_monitor.record_claim_attempt(
  p_writer_lane text,
  p_company_id bigint,
  p_target_table text,
  p_target_criterion smallint,
  p_declared_fact_class text,
  p_detected_fact_class text,
  p_proposed_verdict text,
  p_claim_text text,
  p_payload jsonb,
  p_expected_destination text,
  p_outcome text,
  p_reason text,
  p_source_reference text
)
RETURNS void
LANGUAGE sql
AS $$
  INSERT INTO qa_monitor.claim_write_audit(
    writer_lane, company_id, company_name, target_table, target_criterion,
    declared_fact_class, detected_fact_class, proposed_verdict, claim_text,
    payload, expected_destination, outcome, reason, source_reference
  )
  VALUES (
    p_writer_lane,
    p_company_id,
    (SELECT name FROM public.companies WHERE id = p_company_id),
    p_target_table,
    p_target_criterion,
    p_declared_fact_class,
    p_detected_fact_class,
    p_proposed_verdict,
    p_claim_text,
    COALESCE(p_payload, '{}'::jsonb),
    p_expected_destination,
    p_outcome,
    p_reason,
    p_source_reference
  )
$$;

DROP FUNCTION IF EXISTS public.apply_classified_claim(
  bigint, text, text, text, text, smallint, text, bigint, jsonb
);

CREATE OR REPLACE FUNCTION public.apply_classified_claim(
  p_company_id bigint,
  p_writer_lane text,
  p_fact_class text,
  p_claim_text text,
  p_source_reference text DEFAULT NULL,
  p_criterion integer DEFAULT NULL,
  p_verdict text DEFAULT NULL,
  p_secondary_review_id bigint DEFAULT NULL,
  p_payload jsonb DEFAULT '{}'::jsonb
)
RETURNS TABLE(applied boolean, destination text, detected_fact_class text, reason text)
LANGUAGE plpgsql
AS $$
DECLARE
  v_detected text := qa_monitor.detect_fact_class(p_claim_text);
  v_destination text := qa_monitor.destination_for_fact_class(p_fact_class);
  v_methodology text;
  v_original_verdict text;
  v_actual_verdict text;
  v_actual_rationale text;
  v_actual_methodology text;
  v_scope text;
  v_lifecycle text;
  v_proceeding text;
  v_target text;
  v_amount numeric;
BEGIN
  p_payload := COALESCE(p_payload, '{}'::jsonb);
  applied := false;
  destination := v_destination;
  detected_fact_class := v_detected;
  reason := NULL;

  IF p_criterion IS NULL AND p_fact_class = 'structural' THEN
    destination := CASE p_payload->>'target'
      WHEN 'additionality' THEN 'companies.additionality'
      WHEN 'canonical_decision' THEN 'companies.public_state'
      ELSE v_destination
    END;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.companies WHERE id = p_company_id) THEN
    reason := 'company_not_found';
  ELSIF p_writer_lane IS NULL
        OR p_writer_lane NOT IN ('primary_automation', 'secondary_qa', 'human_adjudication') THEN
    reason := 'invalid_writer_lane';
  ELSIF p_fact_class IS NULL
        OR p_fact_class NOT IN ('structural', 'readiness', 'liveness', 'scope', 'finance') THEN
    reason := 'invalid_fact_class';
  ELSIF p_criterion IS NOT NULL AND p_fact_class <> 'structural' THEN
    reason := 'non_structural_fact_targeted_c1_c8';
  ELSIF p_criterion IS NOT NULL AND v_detected <> 'structural' THEN
    reason := 'phrase_guard_detected_' || v_detected;
  ELSIF p_criterion IS NOT NULL AND (p_criterion < 1 OR p_criterion > 8) THEN
    reason := 'invalid_criterion';
  ELSIF p_criterion IS NOT NULL
        AND (p_verdict IS NULL OR p_verdict NOT IN ('PASS', 'FAIL', 'UNCLEAR')) THEN
    reason := 'invalid_verdict';
  ELSIF p_criterion IS NULL AND p_fact_class = 'structural'
        AND COALESCE(p_payload->>'target', '') NOT IN ('additionality', 'canonical_decision') THEN
    reason := 'structural_claim_requires_criterion_additionality_or_canonical_target';
  END IF;

  IF reason IS NOT NULL THEN
    PERFORM qa_monitor.record_claim_attempt(
      p_writer_lane, p_company_id,
      CASE WHEN p_writer_lane = 'secondary_qa' THEN 'secondary_criterion_reviews' ELSE 'criterion_reviews' END,
      p_criterion::smallint, p_fact_class, v_detected, p_verdict, p_claim_text,
      p_payload, destination, 'rejected', reason, p_source_reference
    );
    RETURN NEXT;
    RETURN;
  END IF;

  IF p_writer_lane = 'primary_automation'
     AND p_fact_class <> 'finance'
     AND EXISTS (
       SELECT 1
       FROM public.companies
       WHERE id = p_company_id
         AND methodology_version ILIKE '%human-adjudicated%'
     ) THEN
    reason := 'human_adjudication_guard_neutralised_write';

    INSERT INTO qa_monitor.guard_audit(
      table_name, company_id, company_name, criterion, blocked_columns,
      attempted_methodology, old_values, attempted_values, db_user, application_name
    )
    SELECT
      CASE WHEN p_criterion IS NULL THEN 'companies' ELSE 'criterion_reviews' END,
      c.id,
      c.name,
      p_criterion::smallint,
      CASE
        WHEN p_criterion IS NOT NULL THEN ARRAY['verdict', 'rationale', 'methodology_version']::text[]
        WHEN p_fact_class = 'readiness' THEN ARRAY['what_it_needs_to_qualify']::text[]
        WHEN p_fact_class = 'liveness' THEN ARRAY['lifecycle_state', 'proceeding_type']::text[]
        WHEN p_fact_class = 'scope' THEN ARRAY['publication_scope']::text[]
        ELSE ARRAY['additionality']::text[]
      END,
      (SELECT value FROM public.system_config WHERE key = 'engine_version'),
      jsonb_build_object(
        'public_state', c.public_state,
        'methodology_version', c.methodology_version
      ),
      jsonb_build_object(
        'fact_class', p_fact_class,
        'verdict', p_verdict,
        'claim_text', p_claim_text,
        'payload', p_payload
      ),
      current_user,
      current_setting('application_name', true)
    FROM public.companies AS c
    WHERE c.id = p_company_id;

    PERFORM qa_monitor.record_claim_attempt(
      p_writer_lane, p_company_id,
      CASE WHEN p_criterion IS NULL THEN destination ELSE 'criterion_reviews' END,
      p_criterion::smallint, p_fact_class, v_detected, p_verdict, p_claim_text,
      p_payload, destination, 'rejected', reason, p_source_reference
    );
    RETURN NEXT;
    RETURN;
  END IF;

  IF p_criterion IS NOT NULL THEN
    IF p_writer_lane = 'secondary_qa' THEN
      IF p_secondary_review_id IS NULL OR NOT EXISTS (
        SELECT 1
        FROM public.secondary_company_reviews
        WHERE id = p_secondary_review_id AND company_id = p_company_id
      ) THEN
        reason := 'secondary_review_not_found_for_company';
      ELSE
        SELECT verdict INTO v_original_verdict
        FROM public.criterion_reviews
        WHERE company_id = p_company_id AND criterion = p_criterion;

        PERFORM set_config('qa_monitor.claim_gate_authorized', '1', true);
        INSERT INTO public.secondary_criterion_reviews(
          secondary_review_id, criterion, original_verdict, proposed_verdict,
          agreement, rationale, missing_evidence, fact_class, writer_lane, source_reference
        )
        VALUES (
          p_secondary_review_id, p_criterion, v_original_verdict, p_verdict,
          v_original_verdict IS NOT DISTINCT FROM p_verdict,
          p_claim_text, p_payload->>'missing_evidence', 'structural', p_writer_lane, p_source_reference
        )
        ON CONFLICT (secondary_review_id, criterion) DO UPDATE SET
          original_verdict = excluded.original_verdict,
          proposed_verdict = excluded.proposed_verdict,
          agreement = excluded.agreement,
          rationale = excluded.rationale,
          missing_evidence = excluded.missing_evidence,
          fact_class = excluded.fact_class,
          writer_lane = excluded.writer_lane,
          source_reference = excluded.source_reference;
        PERFORM set_config('qa_monitor.claim_gate_authorized', '0', true);
        applied := true;
        destination := 'secondary_criterion_reviews';
      END IF;
    ELSE
      v_methodology := COALESCE(
        NULLIF(p_payload->>'methodology_version', ''),
        (SELECT value FROM public.system_config WHERE key = 'engine_version')
      );

      PERFORM set_config('qa_monitor.claim_gate_authorized', '1', true);
      INSERT INTO public.criterion_reviews(
        company_id, criterion, verdict, rationale, reviewed_at, methodology_version,
        fact_class, writer_lane, source_reference
      )
      VALUES (
        p_company_id, p_criterion, p_verdict, p_claim_text, now(), v_methodology,
        'structural', p_writer_lane, p_source_reference
      )
      ON CONFLICT (company_id, criterion) DO UPDATE SET
        verdict = excluded.verdict,
        rationale = excluded.rationale,
        reviewed_at = excluded.reviewed_at,
        methodology_version = excluded.methodology_version,
        fact_class = excluded.fact_class,
        writer_lane = excluded.writer_lane,
        source_reference = excluded.source_reference;
      PERFORM set_config('qa_monitor.claim_gate_authorized', '0', true);

      SELECT verdict, rationale, methodology_version
      INTO v_actual_verdict, v_actual_rationale, v_actual_methodology
      FROM public.criterion_reviews
      WHERE company_id = p_company_id AND criterion = p_criterion;

      IF v_actual_verdict IS DISTINCT FROM p_verdict
         OR v_actual_rationale IS DISTINCT FROM p_claim_text
         OR v_actual_methodology IS DISTINCT FROM v_methodology THEN
        reason := 'human_adjudication_guard_neutralised_write';
      ELSE
        applied := true;
        destination := 'criterion_reviews';
      END IF;
    END IF;
  ELSIF p_fact_class = 'structural' THEN
    IF p_payload->>'target' = 'additionality' THEN
      IF p_payload->>'additionality_state' IS NULL
         OR p_payload->>'additionality_state' NOT IN ('demonstrated', 'plausible', 'weak')
         OR COALESCE(NULLIF(p_payload->>'substitute', ''), '') = ''
         OR COALESCE(NULLIF(p_payload->>'dimension', ''), '') = '' THEN
        reason := 'additionality_requires_state_substitute_and_dimension';
      ELSE
        PERFORM set_config('qa_monitor.claim_gate_authorized', '1', true);
        UPDATE public.companies
        SET additionality_state = p_payload->>'additionality_state',
            additionality_substitute = p_payload->>'substitute',
            additionality_dimension = p_payload->>'dimension',
            additionality_rationale = p_claim_text,
            updated_at = now()
        WHERE id = p_company_id;
        PERFORM set_config('qa_monitor.claim_gate_authorized', '0', true);
        applied := true;
        destination := 'companies.additionality';
      END IF;
    ELSIF p_payload->>'target' = 'canonical_decision' THEN
      IF p_payload->>'public_state' IS NULL
         OR p_payload->>'public_state' NOT IN ('Main', 'Pending', 'Excluded') THEN
        reason := 'canonical_decision_requires_valid_public_state';
      ELSE
        v_methodology := COALESCE(
          NULLIF(p_payload->>'methodology_version', ''),
          (SELECT value FROM public.system_config WHERE key = 'engine_version')
        );
        PERFORM set_config('qa_monitor.claim_gate_authorized', '1', true);
        UPDATE public.companies
        SET public_state = p_payload->>'public_state',
            publishable = (p_payload->>'public_state') <> 'Excluded',
            methodology_version = v_methodology,
            last_reviewed = current_date,
            updated_at = now()
        WHERE id = p_company_id;
        PERFORM set_config('qa_monitor.claim_gate_authorized', '0', true);
        applied := true;
        destination := 'companies.public_state';
      END IF;
    ELSE
      reason := 'invalid_structural_target';
    END IF;
  ELSIF p_fact_class = 'readiness' THEN
    IF p_writer_lane = 'secondary_qa' THEN
      IF p_secondary_review_id IS NULL OR NOT EXISTS (
        SELECT 1 FROM public.secondary_company_reviews
        WHERE id = p_secondary_review_id AND company_id = p_company_id
      ) THEN
        reason := 'secondary_review_not_found_for_company';
      ELSE
        UPDATE public.secondary_company_reviews
        SET what_first_pass_should_do_next_time = CASE
          WHEN COALESCE(NULLIF(p_payload->>'clear', '')::boolean, false) THEN NULL
          ELSE p_claim_text
        END
        WHERE id = p_secondary_review_id;
        applied := true;
        destination := 'secondary_company_reviews.what_first_pass_should_do_next_time';
      END IF;
    ELSE
      PERFORM set_config('qa_monitor.claim_gate_authorized', '1', true);
      UPDATE public.companies
      SET what_it_needs_to_qualify = CASE
            WHEN COALESCE(NULLIF(p_payload->>'clear', '')::boolean, false) THEN NULL
            ELSE p_claim_text
          END,
          updated_at = now()
      WHERE id = p_company_id;
      PERFORM set_config('qa_monitor.claim_gate_authorized', '0', true);
      applied := true;
      destination := 'companies.what_it_needs_to_qualify';
    END IF;
  ELSIF p_fact_class = 'liveness' THEN
    v_lifecycle := NULLIF(p_payload->>'lifecycle_state', '');
    v_proceeding := NULLIF(p_payload->>'proceeding_type', '');
    IF v_lifecycle IS NULL OR v_lifecycle NOT IN (
      'active', 'active_under_protection', 'wound_down',
      'insolvent_liquidated', 'dormant', 'unknown'
    ) THEN
      reason := 'invalid_or_missing_lifecycle_state';
    ELSIF v_proceeding IS NOT NULL
          AND v_proceeding NOT IN ('sauvegarde', 'redressement', 'continuation_plan') THEN
      reason := 'invalid_proceeding_type';
    ELSIF p_writer_lane = 'secondary_qa' THEN
      IF p_secondary_review_id IS NULL OR NOT EXISTS (
        SELECT 1 FROM public.secondary_company_reviews
        WHERE id = p_secondary_review_id AND company_id = p_company_id
      ) THEN
        reason := 'secondary_review_not_found_for_company';
      ELSE
        UPDATE public.secondary_company_reviews
        SET proposed_lifecycle_state = v_lifecycle,
            proposed_proceeding_type = v_proceeding,
            entity_status_rationale = p_claim_text
        WHERE id = p_secondary_review_id;
        applied := true;
        destination := 'secondary_company_reviews.proposed_lifecycle_state';
      END IF;
    ELSE
      PERFORM set_config('qa_monitor.claim_gate_authorized', '1', true);
      UPDATE public.companies
      SET lifecycle_state = v_lifecycle,
          proceeding_type = v_proceeding,
          operating_status = COALESCE(NULLIF(p_payload->>'operating_status', ''), operating_status),
          status_source_url = COALESCE(NULLIF(p_payload->>'status_source_url', ''), status_source_url),
          status_checked_at = COALESCE(NULLIF(p_payload->>'status_checked_at', '')::date, status_checked_at),
          updated_at = now()
      WHERE id = p_company_id;
      PERFORM set_config('qa_monitor.claim_gate_authorized', '0', true);
      applied := true;
      destination := 'companies.lifecycle_state';
    END IF;
  ELSIF p_fact_class = 'scope' THEN
    v_scope := NULLIF(p_payload->>'publication_scope', '');
    IF v_scope IS NULL OR v_scope NOT IN ('in_scope', 'listed', 'acquired') THEN
      reason := 'invalid_or_abolished_publication_scope';
    ELSIF p_writer_lane = 'secondary_qa' THEN
      IF p_secondary_review_id IS NULL OR NOT EXISTS (
        SELECT 1 FROM public.secondary_company_reviews
        WHERE id = p_secondary_review_id AND company_id = p_company_id
      ) THEN
        reason := 'secondary_review_not_found_for_company';
      ELSE
        UPDATE public.secondary_company_reviews
        SET proposed_publication_scope = v_scope
        WHERE id = p_secondary_review_id;
        applied := true;
        destination := 'secondary_company_reviews.proposed_publication_scope';
      END IF;
    ELSE
      PERFORM set_config('qa_monitor.claim_gate_authorized', '1', true);
      UPDATE public.companies
      SET publication_scope = v_scope, updated_at = now()
      WHERE id = p_company_id;
      PERFORM set_config('qa_monitor.claim_gate_authorized', '0', true);
      applied := true;
      destination := 'companies.publication_scope';
    END IF;
  ELSIF p_fact_class = 'finance' THEN
    IF p_writer_lane = 'secondary_qa' THEN
      reason := 'secondary_finance_claim_requires_manual_primary_source_review';
    ELSIF COALESCE(NULLIF(p_payload->>'source_url', ''), '') = '' THEN
      reason := 'finance_requires_primary_source_url';
    ELSE
      v_target := p_payload->>'target';
      v_amount := NULLIF(p_payload->>'amount', '')::numeric;
      IF v_target = 'funding' THEN
        INSERT INTO public.company_funding(
          company_id, round_type, announced_on, amount, currency,
          amount_disclosed, source_url
        ) VALUES (
          p_company_id, p_payload->>'round_type',
          NULLIF(p_payload->>'announced_on', '')::date,
          v_amount, p_payload->>'currency',
          COALESCE(NULLIF(p_payload->>'amount_disclosed', '')::boolean, false),
          p_payload->>'source_url'
        );
        applied := true;
        destination := 'company_funding';
      ELSIF v_target = 'exit' THEN
        INSERT INTO public.company_exit(
          company_id, exit_type, announced_on, amount, currency,
          amount_disclosed, acquirer, source_url
        ) VALUES (
          p_company_id, p_payload->>'exit_type',
          NULLIF(p_payload->>'announced_on', '')::date,
          v_amount, p_payload->>'currency',
          COALESCE(NULLIF(p_payload->>'amount_disclosed', '')::boolean, false),
          p_payload->>'acquirer', p_payload->>'source_url'
        );
        applied := true;
        destination := 'company_exit';
      ELSE
        reason := 'finance_target_must_be_funding_or_exit';
      END IF;
    END IF;
  END IF;

  PERFORM qa_monitor.record_claim_attempt(
    p_writer_lane, p_company_id,
    CASE
      WHEN p_criterion IS NOT NULL AND p_writer_lane = 'secondary_qa' THEN 'secondary_criterion_reviews'
      WHEN p_criterion IS NOT NULL THEN 'criterion_reviews'
      ELSE destination
    END,
    p_criterion::smallint, p_fact_class, v_detected, p_verdict, p_claim_text,
    p_payload, destination,
    CASE WHEN applied THEN 'applied' ELSE 'rejected' END,
    reason, p_source_reference
  );

  RETURN NEXT;
END
$$;

CREATE OR REPLACE FUNCTION qa_monitor.fn_block_direct_claim_dml()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_company_id bigint;
  v_criterion smallint;
  v_fact_class text;
  v_writer text;
  v_claim text;
  v_verdict text;
  v_source text;
BEGIN
  IF current_setting('qa_monitor.claim_gate_authorized', true) = '1' THEN
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
  END IF;

  IF TG_TABLE_NAME = 'criterion_reviews' THEN
    IF TG_OP = 'DELETE' THEN
      v_company_id := OLD.company_id;
      v_criterion := OLD.criterion;
      v_fact_class := OLD.fact_class;
      v_writer := OLD.writer_lane;
      v_claim := OLD.rationale;
      v_verdict := OLD.verdict;
      v_source := OLD.source_reference;
    ELSE
      v_company_id := NEW.company_id;
      v_criterion := NEW.criterion;
      v_fact_class := NEW.fact_class;
      v_writer := NEW.writer_lane;
      v_claim := NEW.rationale;
      v_verdict := NEW.verdict;
      v_source := NEW.source_reference;
    END IF;
  ELSE
    IF TG_OP = 'DELETE' THEN
      SELECT company_id INTO v_company_id
      FROM public.secondary_company_reviews
      WHERE id = OLD.secondary_review_id;
      v_criterion := OLD.criterion;
      v_fact_class := OLD.fact_class;
      v_writer := OLD.writer_lane;
      v_claim := OLD.rationale;
      v_verdict := OLD.proposed_verdict;
      v_source := OLD.source_reference;
    ELSE
      SELECT company_id INTO v_company_id
      FROM public.secondary_company_reviews
      WHERE id = NEW.secondary_review_id;
      v_criterion := NEW.criterion;
      v_fact_class := NEW.fact_class;
      v_writer := NEW.writer_lane;
      v_claim := NEW.rationale;
      v_verdict := NEW.proposed_verdict;
      v_source := NEW.source_reference;
    END IF;
  END IF;

  PERFORM qa_monitor.record_claim_attempt(
    COALESCE(v_writer, 'unknown_direct_writer'), v_company_id, TG_TABLE_NAME,
    v_criterion, v_fact_class, qa_monitor.detect_fact_class(v_claim),
    v_verdict, v_claim, '{}'::jsonb,
    qa_monitor.destination_for_fact_class(v_fact_class),
    'rejected', 'direct_criterion_dml_forbidden', v_source
  );

  IF TG_OP = 'INSERT' OR TG_OP = 'DELETE' THEN
    RETURN NULL;
  END IF;
  RETURN OLD;
END
$$;

DROP TRIGGER IF EXISTS trg_00_classified_claim_gate ON public.criterion_reviews;
CREATE TRIGGER trg_00_classified_claim_gate
BEFORE INSERT OR UPDATE OR DELETE ON public.criterion_reviews
FOR EACH ROW EXECUTE FUNCTION qa_monitor.fn_block_direct_claim_dml();

DROP TRIGGER IF EXISTS trg_00_secondary_claim_gate ON public.secondary_criterion_reviews;
CREATE TRIGGER trg_00_secondary_claim_gate
BEFORE INSERT OR UPDATE OR DELETE ON public.secondary_criterion_reviews
FOR EACH ROW EXECUTE FUNCTION qa_monitor.fn_block_direct_claim_dml();

CREATE OR REPLACE FUNCTION qa_monitor.fn_block_direct_company_claim_dml()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_changed text[] := ARRAY[]::text[];
BEGIN
  IF current_setting('qa_monitor.claim_gate_authorized', true) = '1' THEN
    RETURN NEW;
  END IF;

  IF NEW.public_state IS DISTINCT FROM OLD.public_state THEN v_changed := array_append(v_changed, 'public_state'); END IF;
  IF NEW.publishable IS DISTINCT FROM OLD.publishable THEN v_changed := array_append(v_changed, 'publishable'); END IF;
  IF NEW.what_it_needs_to_qualify IS DISTINCT FROM OLD.what_it_needs_to_qualify THEN v_changed := array_append(v_changed, 'what_it_needs_to_qualify'); END IF;
  IF NEW.methodology_version IS DISTINCT FROM OLD.methodology_version THEN v_changed := array_append(v_changed, 'methodology_version'); END IF;
  IF NEW.last_reviewed IS DISTINCT FROM OLD.last_reviewed THEN v_changed := array_append(v_changed, 'last_reviewed'); END IF;
  IF NEW.lifecycle_state IS DISTINCT FROM OLD.lifecycle_state THEN v_changed := array_append(v_changed, 'lifecycle_state'); END IF;
  IF NEW.proceeding_type IS DISTINCT FROM OLD.proceeding_type THEN v_changed := array_append(v_changed, 'proceeding_type'); END IF;
  IF NEW.operating_status IS DISTINCT FROM OLD.operating_status THEN v_changed := array_append(v_changed, 'operating_status'); END IF;
  IF NEW.status_source_url IS DISTINCT FROM OLD.status_source_url THEN v_changed := array_append(v_changed, 'status_source_url'); END IF;
  IF NEW.status_checked_at IS DISTINCT FROM OLD.status_checked_at THEN v_changed := array_append(v_changed, 'status_checked_at'); END IF;
  IF NEW.publication_scope IS DISTINCT FROM OLD.publication_scope THEN v_changed := array_append(v_changed, 'publication_scope'); END IF;
  IF NEW.additionality_state IS DISTINCT FROM OLD.additionality_state THEN v_changed := array_append(v_changed, 'additionality_state'); END IF;
  IF NEW.additionality_substitute IS DISTINCT FROM OLD.additionality_substitute THEN v_changed := array_append(v_changed, 'additionality_substitute'); END IF;
  IF NEW.additionality_dimension IS DISTINCT FROM OLD.additionality_dimension THEN v_changed := array_append(v_changed, 'additionality_dimension'); END IF;
  IF NEW.additionality_rationale IS DISTINCT FROM OLD.additionality_rationale THEN v_changed := array_append(v_changed, 'additionality_rationale'); END IF;

  IF array_length(v_changed, 1) IS NULL THEN
    RETURN NEW;
  END IF;

  PERFORM qa_monitor.record_claim_attempt(
    'unknown_direct_writer', OLD.id, 'companies', NULL,
    NULL, 'structural', NULL, NULL,
    jsonb_build_object(
      'blocked_columns', to_jsonb(v_changed),
      'attempted_public_state', NEW.public_state,
      'attempted_methodology_version', NEW.methodology_version
    ),
    'public.apply_classified_claim', 'rejected',
    'direct_classification_company_dml_forbidden', NULL
  );

  IF OLD.methodology_version ILIKE '%human-adjudicated%' THEN
    INSERT INTO qa_monitor.guard_audit(
      table_name, company_id, company_name, blocked_columns,
      attempted_methodology, old_values, attempted_values, db_user, application_name
    )
    VALUES (
      'companies', OLD.id, OLD.name, v_changed, NEW.methodology_version,
      jsonb_build_object(
        'public_state', OLD.public_state,
        'publishable', OLD.publishable,
        'methodology_version', OLD.methodology_version
      ),
      jsonb_build_object(
        'public_state', NEW.public_state,
        'publishable', NEW.publishable,
        'methodology_version', NEW.methodology_version
      ),
      current_user, current_setting('application_name', true)
    );
  END IF;

  NEW.public_state := OLD.public_state;
  NEW.publishable := OLD.publishable;
  NEW.what_it_needs_to_qualify := OLD.what_it_needs_to_qualify;
  NEW.methodology_version := OLD.methodology_version;
  NEW.last_reviewed := OLD.last_reviewed;
  NEW.lifecycle_state := OLD.lifecycle_state;
  NEW.proceeding_type := OLD.proceeding_type;
  NEW.operating_status := OLD.operating_status;
  NEW.status_source_url := OLD.status_source_url;
  NEW.status_checked_at := OLD.status_checked_at;
  NEW.publication_scope := OLD.publication_scope;
  NEW.additionality_state := OLD.additionality_state;
  NEW.additionality_substitute := OLD.additionality_substitute;
  NEW.additionality_dimension := OLD.additionality_dimension;
  NEW.additionality_rationale := OLD.additionality_rationale;
  NEW.updated_at := OLD.updated_at;
  RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_00_classified_company_gate ON public.companies;
CREATE TRIGGER trg_00_classified_company_gate
BEFORE UPDATE ON public.companies
FOR EACH ROW EXECUTE FUNCTION qa_monitor.fn_block_direct_company_claim_dml();

INSERT INTO qa_monitor.claim_gate_fixtures(
  fixture_key, company_name, criterion, claim_text,
  expected_fact_class, expected_destination
)
VALUES
  (
    'poppins-c2-readiness',
    'Poppins', 2,
    'The prior randomized trial missed its prespecified primary endpoint and current-version evidence is single-arm; clinically meaningful added benefit over speech therapy/structured literacy is not established.',
    'readiness', 'companies.what_it_needs_to_qualify'
  ),
  (
    'remedee-c2-readiness',
    'Remedee Labs', 2,
    'An open randomized company-funded study reported more responders than usual care, but lacked sham control, bundled device with coaching and could not attribute effect to stimulation; three severe depressive episodes were deemed possibly related. Relative to Medication, exercise, CBT, multidisciplinary pain care and other neuromodulation devices., incremental company-specific benefit is not decisively supported.',
    'readiness', 'companies.what_it_needs_to_qualify'
  ),
  (
    'remedee-c7-readiness',
    'Remedee Labs', 7,
    'Material safety, rebound, privacy, labour or distributional externalities remain unresolved. Excluded: C2/C7 UNCLEAR under strict method; not a Pending because eight PASS are not met.',
    'readiness', 'companies.what_it_needs_to_qualify'
  ),
  (
    'ava-c7-readiness',
    'Ava', 7,
    'Meaning-changing errors can harm education, work and safety.',
    'readiness', 'companies.what_it_needs_to_qualify'
  )
ON CONFLICT (fixture_key) DO UPDATE SET
  company_name = excluded.company_name,
  criterion = excluded.criterion,
  claim_text = excluded.claim_text,
  expected_fact_class = excluded.expected_fact_class,
  expected_destination = excluded.expected_destination;

INSERT INTO qa_monitor.claim_gate_fixtures(
  fixture_key, company_name, criterion, claim_text,
  expected_fact_class, expected_destination
)
SELECT
  'c8-liveness-' || c.id,
  c.name,
  8,
  cr.rationale,
  'liveness',
  'companies.lifecycle_state'
FROM public.criterion_reviews AS cr
JOIN public.companies AS c ON c.id = cr.company_id
WHERE cr.criterion = 8
  AND cr.rationale ILIKE 'Autonomy is structurally disqualifying or under review:%'
ON CONFLICT (fixture_key) DO UPDATE SET
  company_name = excluded.company_name,
  criterion = excluded.criterion,
  claim_text = excluded.claim_text,
  expected_fact_class = excluded.expected_fact_class,
  expected_destination = excluded.expected_destination;

CREATE OR REPLACE VIEW qa_monitor.v_claim_gate_fixture_results AS
SELECT
  f.*,
  qa_monitor.detect_fact_class(f.claim_text) AS detected_fact_class,
  qa_monitor.destination_for_fact_class(qa_monitor.detect_fact_class(f.claim_text)) AS detected_destination,
  qa_monitor.detect_fact_class(f.claim_text) = f.expected_fact_class
    AND qa_monitor.destination_for_fact_class(qa_monitor.detect_fact_class(f.claim_text)) = f.expected_destination
    AS passes
FROM qa_monitor.claim_gate_fixtures AS f;

INSERT INTO public.system_config(key, value, updated_at)
VALUES
  (
    'claim_write_gate',
    'live: public.apply_classified_claim is the only criterion writer; fact classes structural/readiness/liveness/scope/finance; direct criterion DML is neutralised and audited',
    now()
  ),
  (
    'selectivity_rule',
    'C1 problem seriousness; C2 mediation by design; separate additionality with named substitute and dimension; readiness is the only evidence-maturity question',
    now()
  ),
  (
    'harmonic_policy',
    'Harmonic cancelled and forbidden. Funding and exit amounts use primary sources one company at a time, otherwise amount_disclosed=false.',
    now()
  )
ON CONFLICT (key) DO UPDATE
SET value = excluded.value,
    updated_at = excluded.updated_at;

COMMENT ON FUNCTION public.apply_classified_claim IS
  'Single write path for primary automation, secondary QA and human adjudication claims. Rejects and audits non-structural facts aimed at C1-C8.';
