-- Phase 1 correction: make human-adjudication stamps self-verifying.
--
-- A human methodology marker is valid only when it points to a review_feedback
-- row for the same company and the feedback decision agrees with the marker.
-- Every accepted or rejected attempt is written to an append-only audit table.

BEGIN;

CREATE SCHEMA IF NOT EXISTS qa_monitor;

ALTER TABLE public.companies
  ADD COLUMN IF NOT EXISTS human_adjudication_feedback_id bigint,
  ADD COLUMN IF NOT EXISTS human_adjudication_path text;

ALTER TABLE public.criterion_reviews
  ADD COLUMN IF NOT EXISTS human_adjudication_feedback_id bigint,
  ADD COLUMN IF NOT EXISTS human_adjudication_path text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'companies_human_adjudication_path_check'
      AND conrelid = 'public.companies'::regclass
  ) THEN
    ALTER TABLE public.companies
      ADD CONSTRAINT companies_human_adjudication_path_check
      CHECK (
        human_adjudication_path IS NULL OR human_adjudication_path IN (
          'vercel_adjudication', 'migration', 'manual', 'legacy_unrecorded'
        )
      ) NOT VALID;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'criterion_reviews_human_adjudication_path_check'
      AND conrelid = 'public.criterion_reviews'::regclass
  ) THEN
    ALTER TABLE public.criterion_reviews
      ADD CONSTRAINT criterion_reviews_human_adjudication_path_check
      CHECK (
        human_adjudication_path IS NULL OR human_adjudication_path IN (
          'vercel_adjudication', 'migration', 'manual', 'legacy_unrecorded'
        )
      ) NOT VALID;
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS qa_monitor.human_adjudication_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recorded_at timestamptz NOT NULL DEFAULT now(),
  event_kind text NOT NULL CHECK (event_kind IN (
    'stamp_applied',
    'stamp_rejected',
    'legacy_provenance_linked',
    'fabricated_stamp_removed'
  )),
  target_table text NOT NULL CHECK (target_table IN ('companies', 'criterion_reviews')),
  company_id bigint NOT NULL,
  company_name text,
  criterion smallint,
  feedback_id bigint,
  adjudication_path text,
  prior_methodology_version text,
  methodology_version text,
  source_reference text,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  db_user text NOT NULL DEFAULT current_user,
  application_name text DEFAULT current_setting('application_name', true)
);

CREATE INDEX IF NOT EXISTS idx_human_adjudication_audit_company
  ON qa_monitor.human_adjudication_audit(company_id, recorded_at DESC);

CREATE OR REPLACE FUNCTION qa_monitor.fn_block_human_adjudication_audit_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE WARNING 'qa_monitor: human_adjudication_audit is append-only';
  RETURN NULL;
END
$$;

DROP TRIGGER IF EXISTS trg_human_adjudication_audit_append_only
  ON qa_monitor.human_adjudication_audit;
CREATE TRIGGER trg_human_adjudication_audit_append_only
BEFORE UPDATE OR DELETE ON qa_monitor.human_adjudication_audit
FOR EACH ROW EXECUTE FUNCTION qa_monitor.fn_block_human_adjudication_audit_mutation();

-- The 13 category exclusions were stamped in one non-human batch. No migration
-- captured their preceding criterion methodology. Three company-level versions
-- are recoverable from immutable QA snapshots; every other lost value receives
-- an explicit unknown-provenance marker rather than a plausible invention.
CREATE TEMP TABLE phase1_fabricated_stamp_correction (
  company_id bigint PRIMARY KEY,
  restored_company_methodology text NOT NULL
) ON COMMIT DROP;

INSERT INTO phase1_fabricated_stamp_correction(company_id, restored_company_methodology)
VALUES
  (94,   'unknown provenance — fabricated adjudication stamp removed 2026-08-18'),
  (241,  'v3 — strict 8/8 + collapse + additionality'),
  (258,  'unknown provenance — fabricated adjudication stamp removed 2026-08-18'),
  (278,  'unknown provenance — fabricated adjudication stamp removed 2026-08-18'),
  (279,  'unknown provenance — fabricated adjudication stamp removed 2026-08-18'),
  (280,  'unknown provenance — fabricated adjudication stamp removed 2026-08-18'),
  (298,  'unknown provenance — fabricated adjudication stamp removed 2026-08-18'),
  (299,  'unknown provenance — fabricated adjudication stamp removed 2026-08-18'),
  (349,  'unknown provenance — fabricated adjudication stamp removed 2026-08-18'),
  (425,  'v3 — strict 8/8 + collapse + additionality'),
  (458,  'unknown provenance — fabricated adjudication stamp removed 2026-08-18'),
  (1058, 'unknown provenance — fabricated adjudication stamp removed 2026-08-18'),
  (1083, 'v3 — strict 8/8 + collapse + additionality + status/investors + contradiction cross-check');

INSERT INTO qa_monitor.human_adjudication_audit(
  event_kind, target_table, company_id, company_name, criterion,
  adjudication_path, prior_methodology_version, methodology_version,
  source_reference, details
)
SELECT
  'fabricated_stamp_removed', 'companies', c.id, c.name, NULL,
  'migration', c.methodology_version, x.restored_company_methodology,
  'migration:20260818_human_adjudication_provenance',
  jsonb_build_object(
    'reason', 'No review_feedback row existed; the batch stamp did not represent a human decision.',
    'restoration_basis', CASE
      WHEN x.restored_company_methodology LIKE 'v3 —%' THEN 'secondary_company_reviews.primary_methodology_version snapshot'
      ELSE 'prior value not captured; explicit unknown-provenance marker required'
    END
  )
FROM public.companies AS c
JOIN phase1_fabricated_stamp_correction AS x ON x.company_id = c.id
WHERE c.methodology_version ILIKE '%human-adjudicated%'
  AND NOT EXISTS (
    SELECT 1 FROM public.review_feedback AS rf WHERE rf.company_id = c.id
  );

INSERT INTO qa_monitor.human_adjudication_audit(
  event_kind, target_table, company_id, company_name, criterion,
  adjudication_path, prior_methodology_version, methodology_version,
  source_reference, details
)
SELECT
  'fabricated_stamp_removed', 'criterion_reviews', cr.company_id, c.name, cr.criterion,
  'migration', cr.methodology_version,
  'unknown provenance — fabricated adjudication stamp removed 2026-08-18',
  'migration:20260818_human_adjudication_provenance',
  jsonb_build_object(
    'reason', 'No review_feedback row existed; the batch stamp did not represent a human decision.',
    'restoration_basis', 'prior criterion methodology was not captured; explicit unknown-provenance marker required'
  )
FROM public.criterion_reviews AS cr
JOIN public.companies AS c ON c.id = cr.company_id
JOIN phase1_fabricated_stamp_correction AS x ON x.company_id = cr.company_id
WHERE cr.methodology_version ILIKE '%human-adjudicated%'
  AND NOT EXISTS (
    SELECT 1 FROM public.review_feedback AS rf WHERE rf.company_id = cr.company_id
  );

-- Correction is intentionally narrow and is recorded above before the protected
-- triggers are temporarily suspended. Classification, verdict and rationale are
-- not touched.
ALTER TABLE public.companies DISABLE TRIGGER trg_00_classified_company_gate;
ALTER TABLE public.companies DISABLE TRIGGER trg_guard_human_company;
ALTER TABLE public.criterion_reviews DISABLE TRIGGER trg_00_classified_claim_gate;
ALTER TABLE public.criterion_reviews DISABLE TRIGGER trg_guard_human_criterion;

UPDATE public.companies AS c
SET methodology_version = x.restored_company_methodology,
    human_adjudication_feedback_id = NULL,
    human_adjudication_path = NULL
FROM phase1_fabricated_stamp_correction AS x
WHERE c.id = x.company_id
  AND c.methodology_version ILIKE '%human-adjudicated%'
  AND NOT EXISTS (
    SELECT 1 FROM public.review_feedback AS rf WHERE rf.company_id = c.id
  );

UPDATE public.criterion_reviews AS cr
SET methodology_version = 'unknown provenance — fabricated adjudication stamp removed 2026-08-18',
    human_adjudication_feedback_id = NULL,
    human_adjudication_path = NULL
FROM phase1_fabricated_stamp_correction AS x
WHERE cr.company_id = x.company_id
  AND cr.methodology_version ILIKE '%human-adjudicated%'
  AND NOT EXISTS (
    SELECT 1 FROM public.review_feedback AS rf WHERE rf.company_id = cr.company_id
  );

-- Link the six traceable legacy adjudications. The original execution path was
-- not stored, so it is explicitly labelled legacy_unrecorded; the linkage itself
-- is recorded as a migration event.
UPDATE public.companies AS c
SET human_adjudication_feedback_id = rf.id,
    human_adjudication_path = 'legacy_unrecorded'
FROM public.review_feedback AS rf
WHERE rf.company_id = c.id
  AND c.methodology_version ILIKE '%human-adjudicated%'
  AND c.methodology_version = CASE rf.decision
    WHEN 'custom' THEN 'v5 — human-adjudicated custom'
    WHEN 'primary_correct' THEN 'v5 — human-adjudicated primary'
    WHEN 'secondary_correct' THEN 'v5 — human-adjudicated QA'
  END;

UPDATE public.criterion_reviews AS cr
SET human_adjudication_feedback_id = rf.id,
    human_adjudication_path = 'legacy_unrecorded'
FROM public.review_feedback AS rf
WHERE rf.company_id = cr.company_id
  AND cr.methodology_version ILIKE '%human-adjudicated%'
  AND cr.methodology_version = CASE rf.decision
    WHEN 'custom' THEN 'v5 — human-adjudicated custom'
    WHEN 'primary_correct' THEN 'v5 — human-adjudicated primary'
    WHEN 'secondary_correct' THEN 'v5 — human-adjudicated QA'
  END;

INSERT INTO qa_monitor.human_adjudication_audit(
  event_kind, target_table, company_id, company_name, criterion, feedback_id,
  adjudication_path, methodology_version, source_reference, details
)
SELECT
  'legacy_provenance_linked', 'companies', c.id, c.name, NULL,
  c.human_adjudication_feedback_id, c.human_adjudication_path,
  c.methodology_version, 'migration:20260818_human_adjudication_provenance',
  jsonb_build_object(
    'linkage_path', 'migration',
    'original_application_path', 'not previously recorded'
  )
FROM public.companies AS c
WHERE c.methodology_version ILIKE '%human-adjudicated%'
  AND c.human_adjudication_feedback_id IS NOT NULL;

INSERT INTO qa_monitor.human_adjudication_audit(
  event_kind, target_table, company_id, company_name, criterion, feedback_id,
  adjudication_path, methodology_version, source_reference, details
)
SELECT
  'legacy_provenance_linked', 'criterion_reviews', cr.company_id, c.name, cr.criterion,
  cr.human_adjudication_feedback_id, cr.human_adjudication_path,
  cr.methodology_version, 'migration:20260818_human_adjudication_provenance',
  jsonb_build_object(
    'linkage_path', 'migration',
    'original_application_path', 'not previously recorded'
  )
FROM public.criterion_reviews AS cr
JOIN public.companies AS c ON c.id = cr.company_id
WHERE cr.methodology_version ILIKE '%human-adjudicated%'
  AND cr.human_adjudication_feedback_id IS NOT NULL;

ALTER TABLE public.companies ENABLE TRIGGER trg_00_classified_company_gate;
ALTER TABLE public.companies ENABLE TRIGGER trg_guard_human_company;
ALTER TABLE public.criterion_reviews ENABLE TRIGGER trg_00_classified_claim_gate;
ALTER TABLE public.criterion_reviews ENABLE TRIGGER trg_guard_human_criterion;

CREATE OR REPLACE FUNCTION qa_monitor.fn_validate_human_adjudication_stamp()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_company_id bigint;
  v_company_name text;
  v_criterion smallint;
  v_feedback_id bigint;
  v_path text;
  v_expected_methodology text;
  v_source_reference text;
  v_is_new_stamp boolean;
  v_reason text;
BEGIN
  IF TG_TABLE_NAME = 'companies' THEN
    v_company_id := NEW.id;
    v_company_name := NEW.name;
    v_criterion := NULL;
    v_source_reference := current_setting('qa_monitor.human_source_reference', true);
  ELSE
    v_company_id := NEW.company_id;
    v_company_name := (SELECT name FROM public.companies WHERE id = NEW.company_id);
    v_criterion := NEW.criterion;
    v_source_reference := NEW.source_reference;
  END IF;

  IF NEW.methodology_version IS NULL
     OR NEW.methodology_version NOT ILIKE '%human-adjudicated%' THEN
    NEW.human_adjudication_feedback_id := NULL;
    NEW.human_adjudication_path := NULL;
    RETURN NEW;
  END IF;

  BEGIN
    v_feedback_id := NULLIF(
      current_setting('qa_monitor.human_feedback_id', true), ''
    )::bigint;
  EXCEPTION WHEN invalid_text_representation THEN
    v_feedback_id := NULL;
  END;
  v_path := NULLIF(current_setting('qa_monitor.human_adjudication_path', true), '');

  IF v_feedback_id IS NULL THEN
    v_reason := 'human_stamp_requires_feedback_context';
  ELSIF v_path IS NULL OR v_path NOT IN (
    'vercel_adjudication', 'migration', 'manual', 'legacy_unrecorded'
  ) THEN
    v_reason := 'human_stamp_requires_valid_application_path';
  ELSE
    SELECT CASE rf.decision
      WHEN 'custom' THEN 'v5 — human-adjudicated custom'
      WHEN 'primary_correct' THEN 'v5 — human-adjudicated primary'
      WHEN 'secondary_correct' THEN 'v5 — human-adjudicated QA'
    END
    INTO v_expected_methodology
    FROM public.review_feedback AS rf
    WHERE rf.id = v_feedback_id
      AND rf.company_id = v_company_id;

    IF v_expected_methodology IS NULL THEN
      v_reason := 'human_stamp_feedback_not_found_for_company';
    ELSIF NEW.methodology_version IS DISTINCT FROM v_expected_methodology THEN
      v_reason := 'human_stamp_methodology_disagrees_with_feedback_decision';
    END IF;
  END IF;

  IF v_reason IS NOT NULL THEN
    INSERT INTO qa_monitor.human_adjudication_audit(
      event_kind, target_table, company_id, company_name, criterion, feedback_id,
      adjudication_path, prior_methodology_version, methodology_version,
      source_reference, details
    ) VALUES (
      'stamp_rejected', TG_TABLE_NAME, v_company_id, v_company_name, v_criterion,
      v_feedback_id, v_path,
      CASE WHEN TG_OP = 'UPDATE' THEN OLD.methodology_version ELSE NULL END,
      NEW.methodology_version, v_source_reference,
      jsonb_build_object('reason', v_reason, 'operation', TG_OP)
    );

    IF TG_OP = 'INSERT' THEN RETURN NULL; END IF;
    RETURN OLD;
  END IF;

  NEW.human_adjudication_feedback_id := v_feedback_id;
  NEW.human_adjudication_path := v_path;
  -- INSERT ... ON CONFLICT fires the BEFORE INSERT trigger and then the BEFORE
  -- UPDATE trigger. When the criterion already exists, audit only the real
  -- UPDATE event so one adjudication write produces one provenance row.
  v_is_new_stamp := NOT (
      TG_TABLE_NAME = 'criterion_reviews'
      AND TG_OP = 'INSERT'
      AND EXISTS (
        SELECT 1 FROM public.criterion_reviews
        WHERE company_id = v_company_id AND criterion = v_criterion
      )
    ) AND (
      TG_OP = 'INSERT'
      OR OLD.methodology_version IS DISTINCT FROM NEW.methodology_version
      OR OLD.human_adjudication_feedback_id IS DISTINCT FROM v_feedback_id
      OR OLD.human_adjudication_path IS DISTINCT FROM v_path
    );

  IF v_is_new_stamp THEN
    INSERT INTO qa_monitor.human_adjudication_audit(
      event_kind, target_table, company_id, company_name, criterion, feedback_id,
      adjudication_path, prior_methodology_version, methodology_version,
      source_reference, details
    ) VALUES (
      'stamp_applied', TG_TABLE_NAME, v_company_id, v_company_name, v_criterion,
      v_feedback_id, v_path,
      CASE WHEN TG_OP = 'UPDATE' THEN OLD.methodology_version ELSE NULL END,
      NEW.methodology_version, v_source_reference,
      jsonb_build_object('operation', TG_OP)
    );
  END IF;

  RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_05_validate_human_adjudication_stamp ON public.companies;
CREATE TRIGGER trg_05_validate_human_adjudication_stamp
BEFORE INSERT OR UPDATE ON public.companies
FOR EACH ROW EXECUTE FUNCTION qa_monitor.fn_validate_human_adjudication_stamp();

DROP TRIGGER IF EXISTS trg_05_validate_human_adjudication_stamp ON public.criterion_reviews;
CREATE TRIGGER trg_05_validate_human_adjudication_stamp
BEFORE INSERT OR UPDATE ON public.criterion_reviews
FOR EACH ROW EXECUTE FUNCTION qa_monitor.fn_validate_human_adjudication_stamp();

-- The only route that establishes the transaction-local feedback and path
-- context consumed by the validation trigger above.
CREATE OR REPLACE FUNCTION public.apply_human_adjudication_claim(
  p_company_id bigint,
  p_feedback_id bigint,
  p_adjudication_path text,
  p_fact_class text,
  p_claim_text text,
  p_source_reference text DEFAULT NULL,
  p_criterion integer DEFAULT NULL,
  p_verdict text DEFAULT NULL,
  p_secondary_review_id bigint DEFAULT NULL,
  p_payload jsonb DEFAULT '{}'::jsonb
)
RETURNS TABLE(applied boolean, destination text, detected_fact_class text, reason text)
LANGUAGE plpgsql
AS $$
DECLARE
  v_decision text;
  v_expected_methodology text;
BEGIN
  IF p_adjudication_path NOT IN ('vercel_adjudication', 'migration', 'manual') THEN
    RETURN QUERY SELECT false, NULL::text, qa_monitor.detect_fact_class(p_claim_text),
      'invalid_human_adjudication_path'::text;
    RETURN;
  END IF;

  SELECT rf.decision
  INTO v_decision
  FROM public.review_feedback AS rf
  WHERE rf.id = p_feedback_id
    AND rf.company_id = p_company_id
    AND (p_secondary_review_id IS NULL OR rf.secondary_review_id = p_secondary_review_id);

  IF v_decision IS NULL THEN
    RETURN QUERY SELECT false, NULL::text, qa_monitor.detect_fact_class(p_claim_text),
      'review_feedback_not_found_for_company'::text;
    RETURN;
  END IF;

  v_expected_methodology := CASE v_decision
    WHEN 'custom' THEN 'v5 — human-adjudicated custom'
    WHEN 'primary_correct' THEN 'v5 — human-adjudicated primary'
    WHEN 'secondary_correct' THEN 'v5 — human-adjudicated QA'
  END;

  IF (p_criterion IS NOT NULL OR COALESCE(p_payload->>'target', '') = 'canonical_decision')
     AND NULLIF(p_payload->>'methodology_version', '') IS DISTINCT FROM v_expected_methodology THEN
    RETURN QUERY SELECT false, NULL::text, qa_monitor.detect_fact_class(p_claim_text),
      'methodology_disagrees_with_feedback_decision'::text;
    RETURN;
  END IF;

  PERFORM set_config('qa_monitor.human_feedback_id', p_feedback_id::text, true);
  PERFORM set_config('qa_monitor.human_adjudication_path', p_adjudication_path, true);
  PERFORM set_config('qa_monitor.human_source_reference', COALESCE(p_source_reference, ''), true);

  RETURN QUERY
  SELECT * FROM public.apply_classified_claim(
    p_company_id,
    'human_adjudication',
    p_fact_class,
    p_claim_text,
    p_source_reference,
    p_criterion,
    p_verdict,
    p_secondary_review_id,
    COALESCE(p_payload, '{}'::jsonb)
  );

  PERFORM set_config('qa_monitor.human_feedback_id', '', true);
  PERFORM set_config('qa_monitor.human_adjudication_path', '', true);
  PERFORM set_config('qa_monitor.human_source_reference', '', true);
EXCEPTION WHEN OTHERS THEN
  PERFORM set_config('qa_monitor.human_feedback_id', '', true);
  PERFORM set_config('qa_monitor.human_adjudication_path', '', true);
  PERFORM set_config('qa_monitor.human_source_reference', '', true);
  RAISE;
END
$$;

-- Keep the direct company gate aware of the two new protected provenance fields.
CREATE OR REPLACE FUNCTION qa_monitor.fn_block_direct_company_claim_dml()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_changed text[] := ARRAY[]::text[];
BEGIN
  IF current_setting('qa_monitor.claim_gate_authorized', true) = '1' THEN
    RETURN NEW;
  END IF;

  IF NEW.public_state IS DISTINCT FROM OLD.public_state THEN v_changed := array_append(v_changed, 'public_state'); END IF;
  IF NEW.publishable IS DISTINCT FROM OLD.publishable THEN v_changed := array_append(v_changed, 'publishable'); END IF;
  IF NEW.what_it_needs_to_qualify IS DISTINCT FROM OLD.what_it_needs_to_qualify THEN v_changed := array_append(v_changed, 'what_it_needs_to_qualify'); END IF;
  IF NEW.methodology_version IS DISTINCT FROM OLD.methodology_version THEN v_changed := array_append(v_changed, 'methodology_version'); END IF;
  IF NEW.human_adjudication_feedback_id IS DISTINCT FROM OLD.human_adjudication_feedback_id THEN v_changed := array_append(v_changed, 'human_adjudication_feedback_id'); END IF;
  IF NEW.human_adjudication_path IS DISTINCT FROM OLD.human_adjudication_path THEN v_changed := array_append(v_changed, 'human_adjudication_path'); END IF;
  IF NEW.last_reviewed IS DISTINCT FROM OLD.last_reviewed THEN v_changed := array_append(v_changed, 'last_reviewed'); END IF;
  IF NEW.lifecycle_state IS DISTINCT FROM OLD.lifecycle_state THEN v_changed := array_append(v_changed, 'lifecycle_state'); END IF;
  IF NEW.proceeding_type IS DISTINCT FROM OLD.proceeding_type THEN v_changed := array_append(v_changed, 'proceeding_type'); END IF;
  IF NEW.operating_status IS DISTINCT FROM OLD.operating_status THEN v_changed := array_append(v_changed, 'operating_status'); END IF;
  IF NEW.status_source_url IS DISTINCT FROM OLD.status_source_url THEN v_changed := array_append(v_changed, 'status_source_url'); END IF;
  IF NEW.status_checked_at IS DISTINCT FROM OLD.status_checked_at THEN v_changed := array_append(v_changed, 'status_checked_at'); END IF;
  IF NEW.publication_scope IS DISTINCT FROM OLD.publication_scope THEN v_changed := array_append(v_changed, 'publication_scope'); END IF;
  IF NEW.additionality_state IS DISTINCT FROM OLD.additionality_state THEN v_changed := array_append(v_changed, 'additionality_state'); END IF;
  IF NEW.additionality_substitute IS DISTINCT FROM OLD.additionality_substitute THEN v_changed := array_append(v_changed, 'additionality_substitute'); END IF;
  IF NEW.additionality_dimension IS DISTINCT FROM OLD.additionality_dimension THEN v_changed := array_append(v_changed, 'additionality_dimension'); END IF;
  IF NEW.additionality_rationale IS DISTINCT FROM OLD.additionality_rationale THEN v_changed := array_append(v_changed, 'additionality_rationale'); END IF;

  IF array_length(v_changed, 1) IS NULL THEN RETURN NEW; END IF;

  PERFORM qa_monitor.record_claim_attempt(
    'unknown_direct_writer', OLD.id, 'companies', NULL,
    NULL, 'structural', NULL, NULL,
    jsonb_build_object(
      'blocked_columns', to_jsonb(v_changed),
      'attempted_public_state', NEW.public_state,
      'attempted_methodology_version', NEW.methodology_version,
      'attempted_feedback_id', NEW.human_adjudication_feedback_id,
      'attempted_adjudication_path', NEW.human_adjudication_path
    ),
    'public.apply_classified_claim', 'rejected',
    'direct_classification_company_dml_forbidden', NULL
  );

  IF OLD.methodology_version ILIKE '%human-adjudicated%' THEN
    INSERT INTO qa_monitor.guard_audit(
      table_name, company_id, company_name, blocked_columns,
      attempted_methodology, old_values, attempted_values, db_user, application_name
    ) VALUES (
      'companies', OLD.id, OLD.name, v_changed, NEW.methodology_version,
      jsonb_build_object(
        'public_state', OLD.public_state,
        'publishable', OLD.publishable,
        'methodology_version', OLD.methodology_version,
        'feedback_id', OLD.human_adjudication_feedback_id,
        'adjudication_path', OLD.human_adjudication_path
      ),
      jsonb_build_object(
        'public_state', NEW.public_state,
        'publishable', NEW.publishable,
        'methodology_version', NEW.methodology_version,
        'feedback_id', NEW.human_adjudication_feedback_id,
        'adjudication_path', NEW.human_adjudication_path
      ),
      current_user, current_setting('application_name', true)
    );
  END IF;

  NEW.public_state := OLD.public_state;
  NEW.publishable := OLD.publishable;
  NEW.what_it_needs_to_qualify := OLD.what_it_needs_to_qualify;
  NEW.methodology_version := OLD.methodology_version;
  NEW.human_adjudication_feedback_id := OLD.human_adjudication_feedback_id;
  NEW.human_adjudication_path := OLD.human_adjudication_path;
  NEW.last_reviewed := OLD.last_reviewed;
  NEW.lifecycle_state := OLD.lifecycle_state;
  NEW.proceeding_type := OLD.proceeding_type;
  NEW.operating_status := OLD.operating_status;
  NEW.status_source_url := OLD.status_source_url;
  NEW.status_checked_at := OLD.status_checked_at;
  NEW.publication_scope := OLD.publication_scope;
  NEW.additionality_state := OLD.additionality_state;
  NEW.additionality_substitute := OLD.additionality_substitute;
  NEW.additionality_dimension := OLD.additionality_dimension;
  NEW.additionality_rationale := OLD.additionality_rationale;
  NEW.updated_at := OLD.updated_at;
  RETURN NEW;
END
$$;

CREATE OR REPLACE VIEW qa_monitor.v_human_adjudication_provenance AS
WITH stamped AS (
  SELECT
    'companies'::text AS target_table,
    c.id AS company_id,
    c.name AS company_name,
    NULL::smallint AS criterion,
    c.methodology_version,
    c.human_adjudication_feedback_id AS feedback_id,
    c.human_adjudication_path AS adjudication_path
  FROM public.companies AS c
  WHERE c.methodology_version ILIKE '%human-adjudicated%'
  UNION ALL
  SELECT
    'criterion_reviews', cr.company_id, c.name, cr.criterion,
    cr.methodology_version, cr.human_adjudication_feedback_id,
    cr.human_adjudication_path
  FROM public.criterion_reviews AS cr
  JOIN public.companies AS c ON c.id = cr.company_id
  WHERE cr.methodology_version ILIKE '%human-adjudicated%'
)
SELECT
  s.*,
  rf.secondary_review_id,
  rf.decision,
  rf.created_at AS feedback_created_at,
  (
    rf.id IS NOT NULL
    AND rf.company_id = s.company_id
    AND s.adjudication_path IS NOT NULL
    AND s.methodology_version = CASE rf.decision
      WHEN 'custom' THEN 'v5 — human-adjudicated custom'
      WHEN 'primary_correct' THEN 'v5 — human-adjudicated primary'
      WHEN 'secondary_correct' THEN 'v5 — human-adjudicated QA'
    END
  ) AS provenance_valid
FROM stamped AS s
LEFT JOIN public.review_feedback AS rf ON rf.id = s.feedback_id;

CREATE OR REPLACE VIEW qa_monitor.v_human_adjudication_orphans AS
SELECT *
FROM qa_monitor.v_human_adjudication_provenance
WHERE NOT provenance_valid;

ALTER TABLE public.companies
  VALIDATE CONSTRAINT companies_human_adjudication_path_check;
ALTER TABLE public.criterion_reviews
  VALIDATE CONSTRAINT criterion_reviews_human_adjudication_path_check;

INSERT INTO public.system_config(key, value, updated_at)
VALUES (
  'human_adjudication_provenance_gate',
  'live: every human-adjudicated stamp requires same-company review_feedback, decision-matched methodology, a recorded application path, and an append-only audit event',
  now()
)
ON CONFLICT (key) DO UPDATE
SET value = excluded.value, updated_at = excluded.updated_at;

COMMENT ON FUNCTION public.apply_human_adjudication_claim IS
  'Feedback-backed human adjudication writer. Establishes the validated feedback and application-path context before delegating to apply_classified_claim.';

COMMIT;
